top_srcdir   = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
top_builddir = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
srcdir       = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/examples
builddir     = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/examples
VPATH        = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/examples
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
