top_srcdir   = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
top_builddir = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
srcdir       = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/cache
builddir     = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/cache
VPATH        = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/cache

include $(top_srcdir)/build/special.mk

