top_srcdir   = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
top_builddir = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
srcdir       = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/server/mpm/event
builddir     = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/server/mpm/event
VPATH        = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/server/mpm/event
include $(top_srcdir)/build/special.mk
