top_srcdir   = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
top_builddir = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
srcdir       = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules
builddir     = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules
VPATH        = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

