top_srcdir   = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
top_builddir = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
srcdir       = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/server/mpm
builddir     = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/server/mpm
VPATH        = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
