top_srcdir   = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
top_builddir = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
srcdir       = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/os/unix
builddir     = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/os/unix
VPATH        = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
