top_srcdir   = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
top_builddir = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
srcdir       = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/core
builddir     = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/core
VPATH        = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/core

include $(top_srcdir)/build/special.mk

