top_srcdir   = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
top_builddir = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
srcdir       = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/arch/unix
builddir     = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/arch/unix
VPATH        = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/arch/unix

include $(top_srcdir)/build/special.mk

