top_srcdir   = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
top_builddir = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
srcdir       = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/loggers
builddir     = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/loggers
VPATH        = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/loggers

include $(top_srcdir)/build/special.mk

