/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/temoc/TypeChef-GNUCHeader/perl-5.30.2/miniperl ../bin/enc2xs -Q -o ma_04_t.c -f ma_04_t.fnm
 enc2xs VERSION 2.21
*/
extern encode_t MacKorean_encoding;
