top_srcdir   = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
top_builddir = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
srcdir       = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/srclib
builddir     = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/srclib
VPATH        = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
