top_srcdir   = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
top_builddir = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
srcdir       = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/metadata
builddir     = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/metadata
VPATH        = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/metadata

include $(top_srcdir)/build/special.mk

