top_srcdir   = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
top_builddir = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43
srcdir       = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/mappers
builddir     = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/mappers
VPATH        = /home/temoc/TypeChef-GNUCHeader/httpd-2.4.43/modules/mappers

include $(top_srcdir)/build/special.mk

